import {StyleSheet} from 'react-native';
import GST, {wp, hp, colors, fontSize, RF, radius} from '../../../Constant';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.sellerBg,
  },
  headerBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: wp('4%'),
    paddingVertical: hp('1.5%'),
    backgroundColor: colors.sellerCard,
    borderBottomWidth: 1,
    borderBottomColor: colors.sellerBorder,
    elevation: 2,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowOffset: {width: 0, height: 2},
    shadowRadius: 4,
  },
  backButton: {
    marginRight: wp('2%'),
    padding: wp('1%'),
  },
  backArrow: {
    fontSize: RF(22),
    color: colors.sellerPrimary,
  },
  headerAvatar: {
    width: wp('10%'),
    height: wp('10%'),
    borderRadius: wp('5%'),
    backgroundColor: colors.sellerPrimary,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: wp('3%'),
  },
  avatarText: {
    color: colors.white,
    fontSize: fontSize.small,
    fontWeight: '700',
  },
  headerName: {
    fontSize: fontSize.small,
    fontWeight: '600',
    color: colors.sellerText,
  },
  headerRole: {
    fontSize: fontSize.extraSmall,
    color: colors.sellerSuccess,
  },
  chatArea: {
    flex: 1,
    backgroundColor: colors.sellerBg,
  },
  chatList: {
    padding: wp('4%'),
    paddingBottom: hp('1%'),
  },
  messageBubble: {
    padding: wp('3%'),
    borderRadius: radius.radius3,
    marginVertical: hp('0.4%'),
    maxWidth: '80%',
    elevation: 1,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowOffset: {width: 0, height: 1},
    shadowRadius: 2,
  },
  myBubble: {
    alignSelf: 'flex-end',
    backgroundColor: colors.sellerPrimary,
    borderBottomRightRadius: radius.radius1,
  },
  theirBubble: {
    alignSelf: 'flex-start',
    backgroundColor: colors.sellerCard,
    borderWidth: 1,
    borderColor: colors.sellerBorder,
    borderBottomLeftRadius: radius.radius1,
  },
  myMessageText: {
    fontSize: RF(14),
    color: colors.white,
    lineHeight: RF(20),
  },
  theirMessageText: {
    fontSize: RF(14),
    color: colors.sellerText,
    lineHeight: RF(20),
  },
  timeText: {
    fontSize: RF(10),
    marginTop: hp('0.3%'),
    alignSelf: 'flex-end',
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: wp('2%'),
    borderTopWidth: 1,
    borderColor: colors.sellerBorder,
    backgroundColor: colors.sellerCard,
  },
  input: {
    flex: 1,
    backgroundColor: colors.sellerBg,
    borderRadius: wp('5%'),
    paddingHorizontal: wp('4%'),
    paddingVertical: hp('1%'),
    fontSize: RF(14),
    color: colors.sellerText,
    maxHeight: hp('8%'),
    borderWidth: 1,
    borderColor: colors.sellerBorder,
  },
  sendButton: {
    marginLeft: wp('2%'),
    backgroundColor: colors.sellerPrimary,
    paddingVertical: hp('1.2%'),
    paddingHorizontal: wp('5%'),
    borderRadius: wp('5%'),
    elevation: 2,
    shadowColor: colors.sellerPrimary,
    shadowOpacity: 0.3,
    shadowOffset: {width: 0, height: 2},
    shadowRadius: 4,
  },
  sendText: {
    color: colors.white,
    fontWeight: '600',
    fontSize: RF(14),
  },
  centerContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: wp('10%'),
  },
  connectingText: {
    marginTop: hp('1%'),
    fontSize: fontSize.avgSmall,
    color: colors.sellerSubText,
  },
  emptyIcon: {
    width: wp('18%'),
    height: wp('18%'),
    borderRadius: wp('9%'),
    backgroundColor: colors.sellerLight,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: hp('2%'),
  },
  emptyTitle: {
    fontSize: fontSize.small,
    fontWeight: '600',
    color: colors.sellerText,
    marginBottom: hp('0.5%'),
  },
  emptySubtitle: {
    fontSize: fontSize.avgSmall,
    color: colors.sellerSubText,
    textAlign: 'center',
  },
});
